aklish/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("users/", include("users.urls")),
    path("translate/", include("translate.urls")),
    path("dictionary/", include("dictionary.urls")),
    path("dictionary/api/", include("dictionary.api.urls")),
    path("proofreader/", include("proofreader.urls")),
    path("proofreader/api/", include("proofreader.api.urls")),
    path("games/", include("games.urls")),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

dictionary/api/urls.py
from django.urls import path
from . import views


app_name = "dictionary_api"
urlpatterns = [
    path(
        "<str:lang>/entries/", views.ListDictEntryAPIView.as_view(), name="list_entries"
    ),
    path(
        "<str:lang>/entry/<str:word>/",
        views.RetrieveDictEntryAPIView.as_view(),
        name="retrieve_entry",
    ),
    path(
        "<str:lang>/entry/",
        views.RetrieveDictEntryAPIView.as_view(),
        name="retrieve_entry",
    ),
]

dictionary/urls.py
from django.urls import path

from . import views


app_name = "dictionary"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:lang>/entries/", views.catalog, name="catalog"),
    path("<str:lang>/entries/<str:letter>/", views.catalog, name="catalog"),
    path("<str:lang>/entry/<str:word>/", views.entry, name="entry"),
    path("<str:lang>/entry/<str:word>/add_example/<int:attribute_pk>/", views.add_example, name="add_example",),
    path("<str:lang>/word_of_the_day/", views.word_of_the_day, name="word_of_the_day"),
]

main/urls.py
from django.urls import path

from . import views


app_name = "main"
urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("sources/", views.sources, name="sources"),
    path("help/", views.help, name="help"),
    path("help/<str:page>/", views.help, name="help"),
]

translate/urls.py
from django.urls import path

from . import views


app_name = "translate"
urlpatterns = [
    path("entries/", views.catalog, name="catalog"),
    path("entry/<int:entry_pk>/", views.entry, name="entry"),
    path("add/", views.add, name="add"),
    path("edit/entry/<int:entry_pk>/", views.edit_entry, name="edit_entry"),
    path("edit/translation/<int:translation_pk>/", views.edit_translation, name="edit_translation",),
    path("delete/translation/", views.delete_translation, name="delete_translation", ),
    path("delete/entry/", views.delete_entry, name="delete_entry"),
    path("bookmark/<int:entry_pk>/", views.bookmark, name="bookmark"),
    path("vote/<int:translation_pk>/", views.vote, name="vote"),
]

dictionary/api/views.py
import random
import Levenshtein
from django.db.models import Q
from django.db.models.functions import Length
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from django.utils.decorators import method_decorator
from django_ratelimit.decorators import ratelimit
from ..models import DictEntry
from translate.models import Language
from .serializers import DictEntrySerializer


class DictEntryFilter:
    @staticmethod
    def word(queryset, request):
        if words := request.query_params.getlist("word"):
            queryset = queryset.filter(word__in=words)
        if exclude_words := request.query_params.getlist("word!"):
            queryset = queryset.exclude(word__in=exclude_words)

        if word_start := request.query_params.get("word^"):
            queryset = queryset.filter(word__startswith=word_start)
        if word_not_start := request.query_params.get("word!^"):
            queryset = queryset.exclude(word__startswith=word_not_start)

        if word_end := request.query_params.get("word$"):
            queryset = queryset.filter(word__endswith=word_end)
        if word_not_end := request.query_params.get("word!$"):
            queryset = queryset.exclude(word__endswith=word_not_end)

        if word_contains := request.query_params.get("word*"):
            queryset = queryset.filter(word__icontains=word_contains)
        if word_not_contains := request.query_params.get("word!*"):
            queryset = queryset.exclude(word__icontains=word_not_contains)

        if word := request.query_params.get("word_advanced"):
            if "_" in word:
                pattern = "^" + word.replace("_", ".") + "$"
                queryset = queryset.filter(word__regex=pattern)

        casing_condition = request.query_params.get("word_case")
        if casing_condition:
            if casing_condition == "lower":
                queryset = queryset.filter(word__regex=r"^[a-z]+$")
            elif casing_condition == "capitalized":
                queryset = queryset.filter(word__regex=r"^[A-Z][a-z]*$")
            elif casing_condition == "upper":
                queryset = queryset.filter(word__regex=r"^[A-Z]+$")

        if word_len := request.query_params.get("word_len"):
            if "-" in word_len:
                min_length, max_length = map(int, word_len.split("-"))
                queryset = queryset.annotate(word_length=Length("word")).filter(
                    word_length__range=(min_length, max_length)
                )
            else:
                queryset = queryset.annotate(word_length=Length("word")).filter(
                    word_length=int(word_len)
                )

        if levenshtein := request.query_params.get("levenshtein"):
            target_word = levenshtein.strip()
            max_distance = 1
            if max_distance_param := request.query_params.get("max_distance"):
                max_distance = max(int(max_distance_param), 5)
            queryset = queryset.filter(
                Q(
                    word__in=[
                        entry.word
                        for entry in DictEntry.objects.all()
                        if 0
                        < Levenshtein.distance(entry.word, target_word)
                        <= max_distance
                    ]
                )
            )

        return queryset

    @staticmethod
    def definition(queryset, request):
        if definition_start := request.query_params.get("definition^"):
            queryset = queryset.filter(
                attributes__definition__startswith=definition_start
            )
        if definition_not_start := request.query_params.get("definition!^"):
            queryset = queryset.exclude(
                attributes__definition__startswith=definition_not_start
            )

        if definition_end := request.query_params.get("definition$"):
            queryset = queryset.filter(attributes__definition__endswith=definition_end)
        if definition_not_end := request.query_params.get("definition!$"):
            queryset = queryset.exclude(
                attributes__definition__endswith=definition_not_end
            )

        if definition_contains := request.query_params.get("definition*"):
            queryset = queryset.filter(
                attributes__definition__icontains=definition_contains
            )
        if definition_not_contains := request.query_params.get("definition!*"):
            queryset = queryset.exclude(
                attributes__definition__icontains=definition_not_contains
            )

        if definition_len := request.query_params.get("definition_len"):
            if "-" in definition_len:
                min_length, max_length = map(int, definition_len.split("-"))
                queryset = queryset.annotate(
                    definition_length=Length("attributes__definition")
                ).filter(definition_length__range=(min_length, max_length))
            else:
                queryset = queryset.annotate(
                    definition_length=Length("attributes__definition")
                ).filter(definition_length=int(definition_len))

        return queryset

    @staticmethod
    def attribute(queryset, request):
        if poss := request.query_params.getlist("pos"):
            queryset = queryset.filter(attributes__pos__code__in=poss)
        if exclude_poss := request.query_params.getlist("pos!"):
            queryset = queryset.exclude(attributes__pos__code__in=exclude_poss)

        if origins := request.query_params.getlist("origin"):
            queryset = queryset.filter(attributes__origin__code__in=origins)
        if exclude_origins := request.query_params.getlist("origin!"):
            queryset = queryset.exclude(attributes__origin__code__in=exclude_origins)

        if classifications := request.query_params.getlist("classification"):
            queryset = queryset.filter(
                attributes__classification__code__in=classifications
            )
        if exclude_classifications := request.query_params.getlist("classification!"):
            queryset = queryset.exclude(
                attributes__classification__code__in=exclude_classifications
            )

        return queryset

    @staticmethod
    def has(queryset, request):
        if has := request.query_params.getlist("has"):
            if "similar" in has:
                queryset = queryset.filter(attributes__similar__isnull=False)
            if "opposite" in has:
                queryset = queryset.filter(attributes__opposite__isnull=False)

        if has_no := request.query_params.getlist("has!"):
            if "similar" in has_no:
                queryset = queryset.filter(attributes__similar__isnull=True)
            if "opposite" in has_no:
                queryset = queryset.filter(attributes__opposite__isnull=True)

        return queryset


class ListDictEntryAPIView(APIView):
    @method_decorator(ratelimit(key="user_or_ip", rate="60/m"))
    def get(self, request, lang):
        try:
            lang_object = Language.objects.get(code=lang)
        except Language.DoesNotExist:
            return Response(
                {"error": "Language not found"}, status=status.HTTP_404_NOT_FOUND
            )

        dict_entries = DictEntry.objects.filter(lang=lang_object)

        filtered_entries = DictEntryFilter.word(dict_entries, request)
        filtered_entries = DictEntryFilter.definition(filtered_entries, request)
        filtered_entries = DictEntryFilter.attribute(filtered_entries, request)

        if filtered_entries.exists():
            num_entries = self.get_num_entries(request)
            sliced_entries = filtered_entries.order_by("?")[:num_entries]
            serializer = DictEntrySerializer(sliced_entries, many=True)
            return Response(serializer.data)
        else:
            return Response(
                {"error": "No words found matching the criteria"},
                status=status.HTTP_404_NOT_FOUND,
            )

    def get_num_entries(self, request):
        default_num_entries = 5
        num_entries = request.query_params.get("num", default_num_entries)
        try:
            num_entries = int(num_entries)
            num_entries = max(min(num_entries, 10), 1)
        except ValueError:
            num_entries = default_num_entries
        return num_entries


class RetrieveDictEntryAPIView(APIView):
    @method_decorator(ratelimit(key="user_or_ip", rate="60/m"))
    def get(self, request, lang, word=None):
        try:
            lang_object = Language.objects.get(code=lang)
        except Language.DoesNotExist:
            return Response(
                {"error": "Language not found"}, status=status.HTTP_404_NOT_FOUND
            )

        dict_entries = DictEntry.objects.filter(lang=lang_object)

        if word:
            try:
                dict_entry = dict_entries.get(word=word)
                serializer = DictEntrySerializer(dict_entry)
                return Response(serializer.data)
            except DictEntry.DoesNotExist:
                return Response(
                    {"error": "Word not found"}, status=status.HTTP_404_NOT_FOUND
                )
        else:
            filtered_entries = DictEntryFilter.word(dict_entries, request)
            filtered_entries = DictEntryFilter.definition(filtered_entries, request)
            filtered_entries = DictEntryFilter.attribute(filtered_entries, request)
            filtered_entries = DictEntryFilter.has(filtered_entries, request)

            if filtered_entries.exists():
                random_entry = random.choice(filtered_entries)
                serializer = DictEntrySerializer(random_entry)
                return Response(serializer.data)
            else:
                return Response(
                    {"error": "No words found matching the criteria"},

dictionary/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .models import Attribute, DictEntry
from translate.models import Language, Entry

from .helpers import get_word_today


def index(request):
    return redirect("dictionary:catalog", "akl", "a")


def catalog(request, lang, letter=None):
    lang_object = get_object_or_404(Language, code=lang)
    entries = DictEntry.objects.filter(lang=lang_object)

    # Get word of the day
    entry_today = get_word_today(entries)

    # Letter must be a letter or None
    if letter and letter not in "abcdefghijklmnopqrstuvwxyz":
        letter = None

    # Filter entries with letter
    if letter:
        entries = entries.filter(word__startswith=letter)

    # Order entries case-insensitively
    entries = entries.extra(select={"lower_word": "lower(word)"}).order_by("lower_word")

    page = request.GET.get("page") if request.GET.get("page") else 1
    num_entries_to_show = 20

    # Initialize as_translations and filter entries if query exists
    if query := request.GET.get("q"):
        num_entries_to_show = num_entries_to_show / 2

        entries = entries.filter(word__icontains=query)
        as_definitions = entries.filter(attributes__definition__icontains=query)

        # as_definitions pagination
        as_definitions_paginator = Paginator(as_definitions, num_entries_to_show)

        as_definitions_paginated = as_definitions_paginator.get_page(page)
        if int(page) > as_definitions_paginated.paginator.num_pages:
            as_definitions_paginated = None
    else:
        as_definitions_paginated = None

    # entries pagination
    entries_paginator = Paginator(entries, num_entries_to_show)

    entries_paginated = entries_paginator.get_page(page)
    if int(page) > entries_paginated.paginator.num_pages:
        entries_paginated = None

    # Calculate range of page numbers to show
    page_nums_to_show = 6
    start = int(max(1, entries_paginated.number - (page_nums_to_show / 2)))
    end = int(min(start + page_nums_to_show, entries_paginated.paginator.num_pages))
    page_nums = range(start, end + 1)

    return render(request, "dictionary/catalog.html", {
        "query": query or "",
        "entries": entries_paginated,
        "as_definitions": as_definitions_paginated,
        "lang": lang_object,
        "current_letter": letter,
        "page_nums": [str(page_num) for page_num in page_nums],
        "entry_today": entry_today,
    })


@login_required
def entry(request, lang, word):
    lang_object = get_object_or_404(Language, code=lang)
    entry = get_object_or_404(DictEntry, word=word, lang=lang_object)

    return render(request, "dictionary/entry.html", {
        "word": entry.word,
        "attributes": entry.attributes.all().order_by("pos", "classification"),
        "lang": lang_object,
    })


@login_required
def add_example(request, lang, word, attribute_pk):
    lang_object = get_object_or_404(Language, code=lang)
    entry = get_object_or_404(DictEntry, word=word, lang=lang_object)
    attribute = get_object_or_404(Attribute, pk=attribute_pk)

    if request.method == "POST":
        if content := request.POST.get("content"):
            example_entry, created = Entry.objects.get_or_create(
                content=content.strip(),
                lang=lang_object,
                user=request.user,
            )

            attribute.examples.add(example_entry)

            return redirect("dictionary:entry", lang, word)

    return render(request, "dictionary/add_example.html", {
        "word": entry.word,
        "attribute": attribute,
        "lang": lang_object,
    })


def word_of_the_day(request, lang):
    lang_object = get_object_or_404(Language, code=lang)
    entries = DictEntry.objects.filter(lang=lang_object)

    entry = get_word_today(entries)

    return render(request, "dictionary/entry.html", {
        "word": entry.word,
        "attributes": entry.attributes.all().order_by("pos", "classification"),
        "lang": lang_object,
        "word_of_the_day": True,
    })

dictionary/templates/dictionary/add_example.html
{% extends 'dictionary/base.html' %}

{% block title %}
    Add an Example for "{{ word }}"
{% endblock title %}

{% block content %}
    <div class="container pb-3 mb-3 border-bottom">
        <h1 class="fw-normal">Add an example for
            <a href="{% url 'dictionary:entry' lang.code word %}" class="link-unstyled underline-hover">
                '{{ word }}'
            </a>
        </h1>

        <!-- Details -->
        <div>
            <span class="badge bg-primary me-2">{{ lang.name }}</span>
            <span class="me-2 fst-italic text-muted">{{ attribute.pos.meaning }}</span>
            <span class="me-2">{{ attribute.definition }}</span>
        </div>
    </div>

    {% comment %}
    {% if request.user.profile.reputation < 30 %}
        <div class="alert alert-warning">
            You need at least 30 reputation points to add an example. Learn how to gain reputation by visiting the
            <a href="{% url 'main:help' 'reputation_guide' %}" class="text-reset">reputation guide</a>.
        </div>
    {% else %}
    {% endcomment %}
    <!-- Add example form -->
    <div class="container mb-3">
        <form action="{% url 'dictionary:add_example' lang.code word attribute.pk %}" method="POST">
            {% csrf_token %}

            <div class="form-group mb-3 border-bottom">
                <label for="content" class="fw-bold mb-2">Content</label>
                <div id="proofreader-field"></div>
            </div>

            <button class="btn btn-primary">Add example</button>
        </form>
    </div>
    <!-- End add example form -->
{% endblock %}

dictionary/templates/dictionary/base.html
{% extends 'base.html' %}

{% block title %}
    Aklish Dictionary
{% endblock title %}

{% block main %}
    {% block content %}
    {% endblock %}
{% endblock %}

dictionary/templates/dictionary/catalog.html
{% extends 'dictionary/base.html' %}

{% block title %}
    Browse Aklish Dictionary
{% endblock title %}

{% block content %}
    <!-- Header -->
    <div class="container pb-3 mb-3 border-bottom">

        <div class="d-flex align-items-center mb-2">
            <div class="me-auto">
                <h1>{{ lang.name }} Dictionary</h1>
            </div>

            <!-- Language select -->
            <div class="dropdown">
                <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                    Language
                </a>
                <ul class="dropdown-menu">
                    <li><a id="akl" href="{% url 'dictionary:catalog' 'akl' current_letter|default:'a' %}" class="dropdown-item">
                        Aklanon
                    </a></li>
                    <li><a id="eng" href="{% url 'dictionary:catalog' 'eng' currenct_letter|default:'a' %}" class="dropdown-item">
                        English
                    </a></li>
                </ul>
            </div>
            <!-- End language select -->
        </div>

        <!-- Letter pagination -->
        <nav id="letter-pagination" class="mb-2">
            <ul class="pagination pagination-sm flex-wrap justify-content-center m-0">
                {% for letter in 'abcdefghijklmnopqrstuvwxyz' %}
                    <li class="page-item">
                        <a href="{% url 'dictionary:catalog' lang.code letter %}"
                            class="page-link {% if letter == current_letter %}active{% endif %} px-md-2 px-1"
                        >
                            {{ letter|upper }}{{ letter }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </nav>
        <!-- End letter pagination -->

        <!-- Search -->
        <div class="d-flex justify-content-center">
            {% url 'dictionary:catalog' lang.code as catalog_url %}
            {% include 'components/search.html' with url=catalog_url placeholder='Search dictionary' style='max-width: 400px;' %}
        </div>
        <!-- End search -->
    </div>
    <!-- End header -->

    <div class="row g-3">
        {% if entry_today %}
            <div class="col-sm-3">
                <!-- Word of the day -->
                <div class="mb-3">
                    {% include 'dictionary/word_today.html' %}
                </div>
                <!-- End word of the day -->

                <!-- Notices -->
                <div class="alert py-1 px-2 mb-3 alert-info alert-dismissible show" role="alert">
                    <small>
                        <strong>Note: </strong>
                        This dictionary is mainly from our <a href="{% url 'main:sources' %}" class="text-reset">sources</a>
                        and is supplemented by the <a href="{% url 'main:about' %}#team" class="text-reset">lead researchers</a>.
                        It may have missing words and errors.
                    </small>
                    <button type="button" class="btn-close p-2" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                <!-- End notices -->
            </div>
        {% endif %}

        <!-- Lis of entries -->
        <div class="col-sm mb-3">
            <!-- Entries -->
            {% if entries %}
                <ul class="list-group mb-3">
                    {% for entry in entries %}
                        <li class="list-group-item d-flex">
                            <a href="{% url 'dictionary:entry' lang.code entry.word %}" class="me-auto text-decoration-none">
                                {{ entry.word }}
                            </a>
                            <div>
                                <span class="badge text-bg-secondary" style="font-size: xx-small;">
                                    {{ entry.attributes.count }}
                                </span>
                            </div>
                        </li>
                    {% empty %}
                        No entries
                    {% endfor %}
                </ul>
            {% endif %}
            <!-- End entries -->

            <!-- As definitions -->
            {% if as_definitions %}
                <div class="mb-3">
                    <h2 class="h4">"{{ query }}" as definition</h2>
                    <ul class="list-group">
                        {% for entry in as_definitions %}
                            <li class="list-group-item d-flex">
                                <a href="{% url 'dictionary:entry' lang.code entry.word %}" class="me-auto text-decoration-none">
                                    {{ entry.word }}
                                </a>
                                <div>
                                    <span class="badge text-bg-secondary" style="font-size: xx-small;">
                                        {{ entry.attributes.count }}
                                    </span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <!-- End as definitions -->
        </div>
        <!-- End list of entries -->
    </div>

    <!-- Pagination -->
    {% include "components/page_pagination.html" with entries=entries %}
    <!-- End pagination -->
{% endblock %}

dictionary/templates/dictionary/entry.html
{% extends 'dictionary/base.html' %}

{% block title %}
    {{ word }} - Aklish Dictionary
{% endblock title %}

{% block content %}
    <!-- Header -->
    <div class="container pb-3 mb-3 border-bottom">
        <h1>{{ word }}</h1>

        <!-- Tags -->
        <span class="badge bg-primary">{{ lang.name }}</span>
        {% if word_of_the_day %}
            <span class="badge bg-secondary">Word of the day</span>
        {% endif %}
    </div>
    <!-- End header -->

    <!-- Attributes -->
    <div class="container pb-3 mb-3">
        {% comment %}
        {% if request.user.profile.reputation < 10 %}
            <div class="alert alert-warning">
                You need at least 10 reputation points to access word attributes. Learn how to gain reputation by visiting the
                <a href="{% url 'main:help' 'reputation_guide' %}" class="text-reset">reputation guide</a>.
            </div>
        {% else %}
        {% endcomment %}
        <!-- List grouped by pos -->
        <ul class="list-group mb-3">
            {% regroup attributes by pos as pos_list %}

            {% for pos in pos_list %}
                <div class="mb-3">
                    <span class="me-1 fst-italic">
                        {{ pos.grouper.meaning|default:'No POS' }}
                    </span>
                    <ol class="list-group list-group-numbered mb-1">
                        {% for attribute in pos.list %}
                            <li class="list-group-item border-0">
                                <!-- Classification -->
                                {% if attribute.classification %}
                                    <span class="badge text-bg-secondary p-1 px-2 me-1">
                                        {{ attribute.classification.meaning|lower }}
                                    </span>
                                {% endif %}

                                <!-- Definition -->
                                <span>{{ attribute.definition }}</span>
                                <!-- End definition -->

                                <!-- Examples -->
                                <div class="d-flex flex-wrap align-items-center ms-3">
                                    {% for entry in attribute.examples.all %}
                                        <a href="{% url 'translate:entry' entry.pk %}"
                                            class="me-2 link-unstyled underline-hover"
                                            style="font-size: medium; color: grey;"
                                        >
                                            "{{ entry.content }}"
                                        </a>
                                    {% empty %}
                                        <span class="me-1" style="font-size: medium; color: grey;">
                                            Add an example
                                        </span>
                                    {% endfor %}
                                    <a href="{% url 'dictionary:add_example' lang.code word attribute.pk %}"
                                        class="btn btn-secondary rounded-circle p-0"
                                    >
                                        <i class="bi bi-plus-lg mx-1"></i>
                                    </a>
                                </div>
                                <!-- End examples -->

                                <div class="mt-2 ms-3">
                                    <!-- Similar -->
                                    {% if attribute.similar.all %}
                                        <p class="mb-1" style="font-size: small;">
                                            <strong class="fw-normal me-1" style="color: green;">Similar:</strong>
                                            {% for entry in attribute.similar.all %}
                                                <a href="{% url 'dictionary:entry' entry.lang.code entry.word %}"
                                                    class="btn btn-sm rounded-pill border text-muted me-1"
                                                    style="font-size: small;"
                                                >
                                                    {{ entry.word }}
                                                </a>
                                            {% endfor %}
                                        </p>
                                    {% endif %}
                                    <!-- End similar -->

                                    <!-- Opposite -->
                                    {% if attribute.opposite.all %}
                                        <p class="mb-1" style="font-size: small;">
                                            <strong class="fw-normal me-1" style="color: red;">Opposite:</strong>
                                            {% for entry in attribute.opposite.all %}
                                                <a href="{% url 'dictionary:entry' entry.lang.code entry.word %}"
                                                    class="btn btn-sm rounded-pill border text-muted me-1"
                                                    style="font-size: small;"
                                                >
                                                    {{ entry.word }}
                                                </a>
                                            {% endfor %}
                                        </p>
                                    {% endif %}
                                    <!-- End opposite -->

                                    <!-- Origin -->
                                    {% if attribute.origin %}
                                        <p class="text-muted mb-1 border-start border-4 ps-2">
                                            <strong class="fw-normal fst-italic">Origin:</strong>
                                            {{ attribute.origin.meaning }}
                                        </p>
                                    {% endif %}

                                    <!-- Source -->
                                    <strong class="fw-normal fst-italic" style="font-size: smaller;">Sources:</strong>
                                    <ul>
                                        {% for source in attribute.sources.all %}
                                            {% if source %}
                                                <li>
                                                    <a href="{% url 'main:sources' %}"
                                                        class="link-unstyled underline-hover text-muted mb-1"
                                                        style="font-size: smaller;"
                                                    >

                                                        {{ source }}
                                                    </a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </div>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
            {% endfor %}
        </ul>
    </div>
    <!-- End attributes -->
{% endblock %}