aklish/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("users/", include("users.urls")),
    path("translate/", include("translate.urls")),
    path("dictionary/", include("dictionary.urls")),
    path("dictionary/api/", include("dictionary.api.urls")),
    path("proofreader/", include("proofreader.urls")),
    path("proofreader/api/", include("proofreader.api.urls")),
    path("games/", include("games.urls")),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path

from . import views


app_name = "main"
urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("sources/", views.sources, name="sources"),
    path("help/", views.help, name="help"),
    path("help/<str:page>/", views.help, name="help"),
]

translate/urls.py
from django.urls import path

from . import views


app_name = "translate"
urlpatterns = [
    path("entries/", views.catalog, name="catalog"),
    path("entry/<int:entry_pk>/", views.entry, name="entry"),
    path("add/", views.add, name="add"),
    path("edit/entry/<int:entry_pk>/", views.edit_entry, name="edit_entry"),
    path("edit/translation/<int:translation_pk>/", views.edit_translation, name="edit_translation",),
    path("delete/translation/", views.delete_translation, name="delete_translation", ),
    path("delete/entry/", views.delete_entry, name="delete_entry"),
    path("bookmark/<int:entry_pk>/", views.bookmark, name="bookmark"),
    path("vote/<int:translation_pk>/", views.vote, name="vote"),
]

translate/models.py
from django.db import models
from django.contrib.auth.models import User

from proofreader import proofreader


class Language(models.Model):
    code = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=64)

    class Meta:
        unique_together = ("name", "code")

    def __str__(self):
        return f"{self.name} ({self.code})"


class Entry(models.Model):
    content = models.TextField()
    lang = models.ForeignKey(Language, on_delete=models.PROTECT, related_name="entries")
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="entries")
    bookmarks = models.ManyToManyField(User, blank=True, related_name="bookmarks")
    word_count = models.IntegerField(default=0)
    mistake_count = models.IntegerField(default=0)
    correctness = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("content", "lang")

    def update_word_count(self):
        data = proofreader.proofread_text(self.content, lang=self.lang.code)
        self.word_count = proofreader.cal_word_count(data["checks"])

    def update_mistake_count(self):
        data = proofreader.proofread_text(self.content, lang=self.lang.code)
        self.mistake_count = proofreader.cal_mistake_count(data["checks"])

    def update_correctness(self):
        self.correctness = proofreader.cal_correctness(self.word_count, self.mistake_count)

    def save(self, *args, **kwargs):
        self.update_word_count()
        self.update_mistake_count()
        self.update_correctness()
        self.user.profile.update_reputation()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.content} ({self.lang.code}) by {self.user.username}"


class Translation(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE, related_name="translations")
    content = models.TextField()
    lang = models.ForeignKey(Language, on_delete=models.PROTECT, related_name="translations")
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="translations")
    vote_count = models.IntegerField(default=0)
    word_count = models.IntegerField(default=0)
    mistake_count = models.IntegerField(default=0)
    correctness = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("content", "lang", "entry")

    def update_vote_count(self):
        total = 0
        for vote in self.votes.all():
            total += vote.direction
        self.vote_count = total
        self.save()

    def upvote_count(self):
        return self.votes.filter(direction=1).count()

    def downvote_count(self):
        return self.votes.filter(direction=-1).count()

    def update_word_count(self):
        data = proofreader.proofread_text(self.content, lang=self.lang.code)
        self.word_count = proofreader.cal_word_count(data["checks"])

    def update_mistake_count(self):
        data = proofreader.proofread_text(self.content, lang=self.lang.code)
        self.mistake_count = proofreader.cal_mistake_count(data["checks"])

    def update_correctness(self):
        self.correctness = proofreader.cal_correctness(self.word_count, self.mistake_count)

    def save(self, *args, **kwargs):
        self.update_word_count()
        self.update_mistake_count()
        self.update_correctness()
        self.user.profile.update_reputation()
        super().save(*args, **kwargs)

    def __str__(self):
        return (f"{self.entry} to {self.content} ({self.lang.code}) by {self.user.username}")


class Vote(models.Model):
    DIRECTIONS = [
        (1, "upvote"),
        (-1, "downvote"),
    ]

    translation = models.ForeignKey(Translation, on_delete=models.CASCADE, related_name="votes")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="votes")
    direction = models.IntegerField(default=0, choices=DIRECTIONS)

    class Meta:
        unique_together = ("translation", "user")

    def save(self, *args, **kwargs):
        super(Vote, self).save(*args, **kwargs)

        self.translation.update_vote_count()
        self.translation.user.profile.update_reputation()

        if self.direction == 0:
            self.delete()

    def __str__(self):
        return f"{self.direction} ({self.user.username}) ({self.translation.content})"

translate/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import Language, Entry, Translation, Vote

from .helpers import sort_entries


def catalog(request):
    entries = Entry.objects.filter(user__is_active=True)

    # Sort entries
    sort_by = request.GET.get("sort", "latest")
    entries = sort_entries(entries, sort_by)

    # Initialize page number and number of entries to show
    page = request.GET.get("page") if request.GET.get("page") else 1
    num_entries_to_show = 10

    # Initialize as_translations and filter entries if query exists
    if query := request.GET.get("q"):
        num_entries_to_show = num_entries_to_show / 2

        entries = entries.filter(content__icontains=query)
        as_translations = entries.filter(translations__content__icontains=query)

        # as_translations pagination
        as_translations_paginator = Paginator(as_translations, num_entries_to_show)

        as_translations_paginated = as_translations_paginator.get_page(page)
        if int(page) > as_translations_paginated.paginator.num_pages:
            as_translations_paginated = None
    else:
        as_translations_paginated = None

    # entries pagination
    entries_paginator = Paginator(entries, num_entries_to_show)

    entries_paginated = entries_paginator.get_page(page)
    if int(page) > entries_paginated.paginator.num_pages:
        entries_paginated = None

    # Calculate range of page numbers to show
    page_nums_to_show = 6
    start = int(max(1, entries_paginated.number - (page_nums_to_show / 2)))
    end = int(min(start + page_nums_to_show, entries_paginated.paginator.num_pages))
    page_nums = range(start, end + 1)

    return render(request, "translate/catalog.html", {
        "query": query or "",
        "entries": entries_paginated,
        "entries_count": entries.count(),
        "as_translations": as_translations_paginated,
        "page_nums": [str(page_num) for page_num in page_nums],
        "sort_by": sort_by,
    })


def entry(request, entry_pk):
    entry = get_object_or_404(Entry, pk=entry_pk)

    # Get bookmark status
    bookmarked = False
    if entry.bookmarks.filter(pk=request.user.id).exists():
        bookmarked = True

    # Get translations
    translations = sorted(entry.translations.all(), key=lambda t: t.vote_count, reverse=True)

    # Add translation
    if request.method == "POST":
        lang = request.POST.get("lang")
        content = request.POST.get("content")

        if lang != entry.lang.code and content:
            lang_object = get_object_or_404(Language, code=lang)
            translation, created = Translation.objects.get_or_create(
                entry=entry, lang=lang_object, content=content.strip(), user=request.user
            )
            if not created:
                return render(request, "translate/entry.html", {
                    "entry": entry,
                    "bookmarked": bookmarked,
                    "translations": translations,
                    "message": "Translation already exists."
                })

    return render(request, "translate/entry.html", {
        "entry": entry,
        "bookmarked": bookmarked,
        "translations": translations,
    })


@login_required
def add(request):
    if request.method == "POST":
        lang = request.POST.get("lang")
        content = request.POST.get("content")

        if lang and content:
            lang_object = get_object_or_404(Language, code=lang)
            entry, created = Entry.objects.get_or_create(lang=lang_object, content=content.strip(), user=request.user)
            if not created:
                return render(request, "translate/add.html", {"message": "Entry already exists."})
            return redirect("translate:entry", entry.pk)

    return render(request, "translate/add.html")


@login_required
def edit_entry(request, entry_pk):
    entry = get_object_or_404(Entry, pk=entry_pk)

    if request.method == "POST" and entry.user == request.user:
        if content := request.POST.get("content"):
            entry.content = content.strip()
            entry.save()

        return redirect("translate:entry", entry.pk)

    return render(request, "translate/edit_entry.html", {
        "entry": entry,
    })


@login_required
def edit_translation(request, translation_pk):
    translation = get_object_or_404(Translation, pk=translation_pk)

    if request.method == "POST" and translation.user == request.user:
        if content := request.POST.get("content"):
            translation.content = content.strip()
            translation.save()

        return redirect("translate:entry", translation.entry.pk)

    return render(request, "translate/edit_translation.html", {
        "translation": translation,
    })


@login_required
def delete_entry(request):
    if request.method == "POST":
        entry_pk = request.POST.get("entry_pk")

        entry = get_object_or_404(Entry, pk=entry_pk)

        if entry.user == request.user:
            entry.delete()

    if next := request.GET.get("next"):
        return redirect(next)

    return redirect("translate:catalog")


@login_required
def delete_translation(request):
    if request.method == "POST":
        translation_pk = request.POST.get("translation_pk")

        translation = get_object_or_404(Translation, pk=translation_pk)

        if translation.user == request.user:
            translation.delete()

    if next := request.GET.get("next"):
        return redirect(next)

    return redirect("translate:entry", translation.entry.pk)


@login_required
def bookmark(request, entry_pk):
    entry = get_object_or_404(Entry, pk=entry_pk)

    if request.method == "POST" and request.user != entry.user:
        if entry.bookmarks.filter(pk=request.user.id).exists():
            entry.bookmarks.remove(request.user)
        else:
            entry.bookmarks.add(request.user)

    return redirect("translate:entry", entry_pk)


@login_required
def vote(request, translation_pk):
    translation = get_object_or_404(Translation, pk=translation_pk)

    if request.method == "POST" and request.user != translation.user:
        vote = Vote.objects.get_or_create(translation=translation, user=request.user)[0]
        direction = request.POST.get("direction")
        if direction in ("1", "-1") :
            direction = int(direction)
            if vote.direction != direction:
                vote.direction = direction
                vote.save()
            else:
                vote.delete()
        else:
            vote.delete()

    return redirect("translate:entry", translation.entry.pk)

translate/templates/translate/add.html
{% extends 'translate/base.html' %}

{% block title %}
    Add an Entry to Aklish
{% endblock title %}

{% block content %}
    <div class="container pb-3 mb-3 border-bottom">
        <h1>Add an entry</h1>
    </div>

    <!-- Add entry guide -->
    <div class="container">
        <div class="alert py-1 px-2 alert-info alert-dismissible show" role="alert">
            <small>
                Please review this
                <a href="{% url 'main:help' 'adding_guide' %}" class="text-reset">guide</a>
                before adding any entry.
            </small>
            <button type="button" class="btn-close p-2" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
    <!-- End add entry guide -->

    <!-- Add entry form -->
    <div class="container">
        {% if message %}
            <div class="alert alert-warning px-2 py-1" role="alert">
                {{ message }}
            </div>
        {% endif %}

        <form action="{% url 'translate:add' %}" method="POST">
            {% csrf_token %}

            <div class="form-group mb-3">
                <label for="lang" class="fw-bold mb-2">Language</label>
                <select name="lang" id="lang" class="form-select mb-2">
                    <option value="akl">Aklanon</option>
                    <option value="eng">English</option>
                </select>
            </div>

            <div class="form-group mb-3">
                <label for="content" class="fw-bold mb-2">Content</label>
                <div id="proofreader-field"></div>
            </div>

            <button class="btn btn-primary">Add entry</button>
        </form>
    </div>
    <!-- End add entry form -->
{% endblock %}

translate/templates/translate/base.html
{% extends 'base.html' %}

{% block title %}
    Aklish Translate
{% endblock title %}

{% block main %}
    {% block content %}
    {% endblock %}
{% endblock %}

translate/templates/translate/catalog.html
{% extends 'translate/base.html' %}

{% block title %}
    Browse Aklish
{% endblock title %}

{% load humanize %}

{% block content %}
    <!-- Header -->
    <div class="container pb-3 mb-3 border-bottom">

        <div class="d-flex align-items-center mb-3">
            <h1 class="me-auto">{{ entries_count }} entries</h1>
            <div>
                <a href="{% url 'translate:add' %}" class="btn btn-primary mb-1">Add entry</a>
            </div>
        </div>

        <div class="row g-2 align-items-center">
            <!-- Sort entries -->
            <div class="col-md">
                <ul class="nav nav-pills nav-fill nav-justified p-1 m-0 rounded-pill border">
                    <!-- Sort options -->
                    <li class="nav-item">
                        <a href="?sort=latest&q={{ query }}"
                            class="nav-link p-0 rounded-pill {% if sort_by == 'latest' %} active {% endif %}"
                        >
                            Latest
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="?sort=top&q={{ query }}"
                            class="nav-link p-0 rounded-pill {% if sort_by == 'top' %} active {% endif %}"
                        >
                            Top
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="?sort=reputable&q={{ query }}"
                            class="nav-link p-0 rounded-pill {% if sort_by == 'reputable' %} active {% endif %}"
                        >
                            Reputable
                        </a>
                    </li>
                    <!-- End options -->

                    <!-- More options -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle p-0 rounded-pill"
                            role="button" data-bs-toggle="dropdown" href="#"
                        >
                            More
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="?sort=proofread&q={{ query }}">
                                    Proofread
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="?sort=translated&q={{ query }}">
                                    Translated
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="?sort=untranslated&q={{ query }}">
                                    Untranslated
                                </a>
                            </li>
                        </ul>
                    </li>
                    <!-- End more options -->
                </ul>
            </div>
            <!-- End sort entries -->

            <!-- Search entries -->
            <div class="col-md">
                {% url 'translate:catalog' as catalog_url %}
                {% include "components/search.html" with url=catalog_url placeholder='Search entries' sort_by=sort_by %}
            </div>
            <!-- End search entries -->
        </div>
    </div>
    <!-- End header -->

    <!-- Notices -->
    <div class="container">
        <div class="alert py-1 px-2 alert-info alert-dismissible show" role="alert">
            <small>
                <strong>Note: </strong>
                The following entries and translations are user-generated;
                they are not guaranteed for validity.
            </small>
            <button type="button" class="btn-close p-2" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
    <!-- End notices -->

    <!-- List of entries -->
    <div class="container">
        <!-- Entries -->
        <div class="mb-3">
            {% for entry in entries %}
                {% include "translate/components/entry_card.html" with entry=entry %}
            {% empty %}
                No entries
            {% endfor %}
        </div>
        <!-- End entries -->

        <!-- As translations -->
        {% if as_translations %}
            <div class="mb-3">
                <h2 class="h4">"{{ query }}" as translation</h2>

                {% for entry in as_translations %}
                    {% include "translate/components/entry_card.html" with entry=entry %}
                {% endfor %}
            </div>
        {% endif %}
        <!-- End as translations -->
    </div>
    <!-- End list of entries -->

    <!-- Pagination -->
    {% include "components/page_pagination.html" with entries=entries %}
    <!-- End pagination -->
{% endblock %}

translate/templates/translate/edit_entry.html
{% extends 'translate/base.html' %}

{% block title %}
    Edit entry for "{{ entry.content|slice:20 }}..."
{% endblock title %}

{% block content %}
    <div class="container pb-3 mb-3 border-bottom">
        <h1>Edit entry</h1>
        <div>
            <span class="badge bg-primary mb-2">{{ entry.lang.name }}</span>
        </div>
    </div>

    <div class="container mb-3">
        <!-- Old content -->
        <label class="fw-bold mb-2">Old content</label>
        {{ entry.content|linebreaks }}
        <!-- End old content -->

        <!-- New content form -->
        <form id="edit-entry" action="{% url 'translate:edit_entry' entry.pk %}" method="POST">
            {% csrf_token %}

            <div class="form-group mb-3 border-bottom">
                <label for="content" class="fw-bold mb-2">New content</label>
                <div id="proofreader-field">
                </div>
            </div>
        </form>
        <!-- End new content form -->

        <!-- Delete entry form -->
        <form id="delete-entry" action="{% url 'translate:delete_entry' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="entry_pk" value="{{ entry.pk }}">
        </form>
        <!-- End delete entry form -->

        <!-- Actions -->
        <div class="d-flex">
            <button class="btn btn-primary me-auto" form="edit-entry">Save changes</button>
            <button class="btn btn-danger" form="delete-entry">Delete</button>
        </div>
        <!-- End actions -->
    </div>
{% endblock %}

translate/templates/translate/edit_translation.html
{% extends 'translate/base.html' %}

{% block title %}
    Edit translation for "{{ translation.content|slice:20 }}..."
{% endblock title %}

{% block content %}
    <div class="container pb-3 mb-3 border-bottom">
        <h1>Edit translation for</h1>
        <div>
            <span class="badge bg-primary mb-2">{{ translation.entry.lang.name }}</span>
            {{ translation.entry.content|linebreaks }}
        </div>
    </div>

    <div class="container mb-3">
        <!-- Old translation -->
        <label class="fw-bold mb-2">Old translation</label>
        {{ translation.content|linebreaks }}
        <!-- End old translation -->

        <!-- New translation form -->
        <form id="edit-translation" action="{% url 'translate:edit_translation' translation.pk %}" method="POST">
            {% csrf_token %}

            <div class="form-group mb-3 border-bottom">
                <label for="content" class="fw-bold mb-2">New translation</label>
                <div id="proofreader-field">
                </div>
            </div>
        </form>
        <!-- End new translation form -->

        <!-- Delete translation form-->
        <form id="delete-translation" action="{% url 'translate:delete_translation' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="translation_pk" value="{{ translation.pk }}">
        </form>
        <!-- End delete translation form -->

        <!-- Actions -->
        <div class="d-flex">
            <button class="btn btn-primary me-auto" form="edit-translation">Save changes</button>
            <button class="btn btn-danger" form="delete-translation">Delete</button>
        </div>
        <!-- End actions -->
    </div>
{% endblock %}

translate/templates/translate/entry.html
{% extends 'translate/base.html' %}

{% load humanize %}
{% load translate_tags %}

{% block title %}
    "{{ entry.content|slice:25 }}..." - Aklish Entry
{% endblock title %}

{% block content %}
    <!-- Entry -->
    <div class="container d-flex pb-3 mb-4 border-bottom">
        <!-- Bookmark button -->
        <div class="me-3 text-center">
            <form action="{% url 'translate:bookmark' entry.pk %}" method="POST">
                {% csrf_token %}

                <button class="btn btn-unstyled border-0 shadow-none" title="Bookmark" aria-label="Bookmark"
                    {% if request.user == entry.user %} disabled {% endif %}
                >
                    <i class="bi bi-bookmark{% if bookmarked %}-fill{% endif %} text-primary"></i>
                </button>
                <div class="my-1">{{ entry.bookmarks.count }}</div>
            </form>
        </div>
        <!-- End bookmark button -->

        <div class="flex-grow-1">
            <!-- Entry content -->
            {{ entry.content|linebreaks }}
            <!-- End entry content -->

            <!-- Entry details -->
            {% include "translate/components/entry_footer.html" with entry=entry %}
            <!-- End entry details -->
        </div>
    </div>
    <!-- End entry -->

    <!-- Translations -->
    <div class="container">
        <h2 class="h5 mb-4">{{ translations_votes|length }} Translations</h2>

        <!-- List of translations -->
        {% for translation in translations %}
            <div class="d-flex pb-3 mb-4 border-bottom">
                <!-- Vote buttons -->
                <div class="me-3 text-center">
                    <form action="{% url 'translate:vote' translation.pk %}" method="POST">
                        {% csrf_token %}

                        {% with vote=translation|get_user_vote:request.user %}
                            <!-- Upvote -->
                            <button name="direction" value="1"
                                class="btn btn-sm btn{% if vote.direction != 1 %}-outline{% endif %}-primary rounded-circle"
                                title="Upvote" aria-label="Upvote"
                                {% if request.user == translation.user %} disabled {% endif %}
                            >
                                <i class="bi bi-caret-up-fill"></i>
                            </button>

                            <!-- Vote count -->
                            <div class="my-1">{{ translation.vote_count }}</div>

                            <!-- Downvote -->
                            <button name="direction" value="-1"
                                class="btn btn-sm btn{% if vote.direction != -1 %}-outline{% endif %}-primary rounded-circle"
                                title="Downvote" aria-label="Downvote"
                                {% if request.user == translation.user %} disabled {% endif %}
                            >
                                <i class="bi bi-caret-down-fill"></i>
                            </button>
                        {% endwith %}
                    </form>
                </div>
                <!-- End vote buttons -->

                <div class="flex-grow-1">
                    <!-- Translation content -->
                    {{ translation.content|linebreaks }}
                    <!-- End translations content -->

                    {% include "translate/components/entry_footer.html" with entry=translation %}
                </div>
            </div>
        {% empty %}
            <div class="pb-3 mb-4 border-bottom">
                No translations
            </div>
        {% endfor %}
        <!-- List of translations -->
    </div>
    <!-- End translations -->

    <!-- Translation guide -->
    <div class="container">
        <div class="alert py-1 px-2 alert-info alert-dismissible show" role="alert">
            <small>
                Please review this
                <a href="{% url 'main:help' 'translating_guide' %}" class="text-reset">guide</a>
                before translating any entry.
            </small>
            <button type="button" class="btn-close p-2" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
    <!-- End translations guide -->

    <!-- Add translation -->
    <div class="container">
        <div class="col-md">
            <h2 class="h5 mb-3">Add translation</h2>

            {% if message %}
                <div class="alert alert-warning px-2 py-1" role="alert">
                    {{ message }}
                </div>
            {% endif %}

            <form action="{% url 'translate:entry' entry.id %}" method="POST" id="add-translation">
                {% csrf_token %}

                <input type="hidden" name="entry_lang" value="{{ entry.lang.code }}" id="entry-lang">

                <div class="form-group mb-3">
                    <label for="lang" class="fw-bold mb-2">Language</label>
                    <select name="lang" id="lang" class="form-select mb-2">
                        <option value="akl">Aklanon</option>
                        <option value="eng">English</option>
                    </select>
                </div>

                <div class="form-group mb-3">
                    <label for="content" class="fw-bold mb-2">Content</label>
                    <div id="proofreader-field"></div>
                </div>

                <div class="form-group mb-3">
                    <input type="checkbox" name="reverse" id="reverse">
                    <label for="reverse">Also add translation as entry</label>
                </div>

                <button class="btn btn-primary">Add translation</button>
            </form>
        </div>
    </div>
    <!-- End add translation -->

    <script>
        const translationLangSelect = document.querySelector("#lang");
        const entryLang = document.querySelector("#entry-lang");

        for (const option of translationLangSelect.options) {
            option.selected = option.value !== entryLang.value;
            option.disabled = option.value === entryLang.value;
        }
    </script>
{% endblock %}