aklish/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("users/", include("users.urls")),
    path("translate/", include("translate.urls")),
    path("dictionary/", include("dictionary.urls")),
    path("dictionary/api/", include("dictionary.api.urls")),
    path("proofreader/", include("proofreader.urls")),
    path("proofreader/api/", include("proofreader.api.urls")),
    path("games/", include("games.urls")),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path

from . import views


app_name = "main"
urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("sources/", views.sources, name="sources"),
    path("help/", views.help, name="help"),
    path("help/<str:page>/", views.help, name="help"),
]

translate/urls.py
from django.urls import path

from . import views


app_name = "translate"
urlpatterns = [
    path("entries/", views.catalog, name="catalog"),
    path("entry/<int:entry_pk>/", views.entry, name="entry"),
    path("add/", views.add, name="add"),
    path("edit/entry/<int:entry_pk>/", views.edit_entry, name="edit_entry"),
    path("edit/translation/<int:translation_pk>/", views.edit_translation, name="edit_translation",),
    path("delete/translation/", views.delete_translation, name="delete_translation", ),
    path("delete/entry/", views.delete_entry, name="delete_entry"),
    path("bookmark/<int:entry_pk>/", views.bookmark, name="bookmark"),
    path("vote/<int:translation_pk>/", views.vote, name="vote"),
]

user/urls.py
from django.urls import path
from . import views


app_name = "user"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:user_id>/<str:username>", views.profile, name="profile"),
    # path("profile", views.profile, name="profile"),
    path("register", views.register, name="register"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout")
]

users/urls.py
from django.urls import path

from . import views


app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:user_id>/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/<str:username>/bookmarks_votes/", views.bookmarks_votes, name="bookmarks_votes",),
    path("<int:user_id>/<str:username>/entries_translations/", views.entries_translations, name="entries_translations",),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class LoginSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="login_session")
    login_at = models.DateTimeField(default=timezone.now)
    logout_at = models.DateTimeField(null=True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    login_count = models.IntegerField(default=0)
    reputation = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.username}"

    def update_reputation(self):
        user = self.user

        reputation = 0

        for entry in user.entries.all():
            reputation += 1

            reputation += entry.bookmarks.all().count() * 2

        for translation in user.translations.all():
            reputation += 1

            upvote_points = translation.upvote_count() * 10
            reputation += upvote_points + upvote_points * (translation.correctness / 100)
            downvote_points = translation.downvote_count() * 5
            reputation -= downvote_points - downvote_points * (translation.correctness / 100)

        self.reputation = round(reputation)
        self.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]

        widgets = {
            "username": forms.TextInput(
                attrs={"class": "form-control mb-2", "autofocus": "true", "placeholder": "Username"}
            ),
            "email": forms.TextInput(
                attrs={"required": "true", "class": "form-control mb-2", "placeholder": "Email"}
            ),
            "first_name": forms.TextInput(
                attrs={"required": "true", "class": "form-control mb-2", "placeholder": "First name"}
            ),
            "last_name": forms.TextInput(
                attrs={"required": "true", "class": "form-control mb-2", "placeholder": "Last name"}
            ),
        }

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control mb-2", "placeholder": "Password"})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control mb-2", "placeholder": "Confirm password"})
    )


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control mb-2", "autofocus": "true", "placeholder": "Username"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control mb-2", "placeholder": "Password"}
            )
    )

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from translations.models import Language, Entry, Translation
from .forms import RegisterForm, LoginForm


@login_required(login_url="user:login")
def index(request):
    return redirect("user:profile")


def profile(request, user_id, username):
    if request.method == "POST":
        if request.POST.get("remove_bookmark"):
            entry_to_unbookmark_pk = request.POST.get("entry_to_unbookmark_pk")
            entry_to_unbookmark = Entry.objects.get(pk=entry_to_unbookmark_pk)
            entry_to_unbookmark.bookmarks.remove(request.user)

        if request.POST.get("delete_entry"):
            entry_to_delete_pk = request.POST.get("entry_to_delete_pk")
            entry_to_delete = Entry.objects.get(pk=entry_to_delete_pk)
            entry_to_delete.delete()
        
        if request.POST.get("delete_translation"):
            translation_to_delete_pk = request.POST.get("translation_to_delete_pk")
            translation_to_delete = Translation.objects.get(pk=translation_to_delete_pk)
            translation_to_delete.delete()
        
        return redirect("user:profile", request.user.pk, request.user.username)

    user = User.objects.get(pk=user_id, username=username)
    return render(request, "user/profile.html", {
        "user": user,
    })


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect("user:login")
    else:
        form = RegisterForm()

    return render(request, "user/register.html", {
        "form": form
    })


def login(request):
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")

            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth.login(request, user)

                return redirect("translations:homepage")
    else:
        form = LoginForm()

    return render(request, "user/login.html", {
        "form": form
    })


def logout(request):
    auth.logout(request)

    return redirect("translations:homepage")

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.utils import timezone

from .models import LoginSession
from .forms import RegisterForm, LoginForm


def index(request):
    users = User.objects.order_by("-profile__reputation", "date_joined").filter(is_active=True).filter(is_staff=False)

    return render(request, "users/index.html", {
        "users": users
    })


def profile(request, user_id, username):
    user = get_object_or_404(User, pk=user_id, username=username)

    return render(request, "users/profile.html", {
        "user": user,
    })


def bookmarks_votes(request, user_id, username):
    user = get_object_or_404(User, pk=user_id, username=username)

    return render(request, "users/bookmarks_votes.html", {
        "user": user,
    })


def entries_translations(request, user_id, username):
    user = get_object_or_404(User, pk=user_id, username=username)
    return render(request, "users/entries_translations.html", {
        "user": user,
    })


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()

            username = request.POST.get("username")
            password = request.POST.get("password1")

            user = authenticate(request, username=username, password=password)

            auth.login(request, user)

            user.profile.login_count += 1
            user.profile.save()

            LoginSession.objects.create(user=user, login_at=timezone.now(),)

            next_page = request.GET.get("next", "/")
            return redirect(next_page)
    else:
        form = RegisterForm()

    return render(request, "users/register.html", {"form": form})


def login(request):
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")

            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth.login(request, user)

                user.profile.login_count += 1
                user.profile.save()

                LoginSession.objects.create(user=user, login_at=timezone.now(),)

                next_page = request.GET.get("next", "/")
                return redirect(next_page)
    else:
        form = LoginForm()

    return render(request, "users/login.html", {"form": form})


def logout(request):
    if request.user.is_authenticated:
        last_login_session = LoginSession.objects.filter(user=request.user, logout_at=None).order_by("-login_at").first()
        if last_login_session:
            last_login_session.logout_at = timezone.now()
            last_login_session.save()

    auth.logout(request)

    return redirect("main:homepage")

users/templates/users/about_reputation.html
{% extends 'users/base.html' %}

{% load humanize %}

{% block title %}
    About Aklish Reputation Points
{% endblock title %}

{% block content %}
    <div class="container pb-3 mb-3 border-bottom">
        <h1>About User Reputation</h1>
    </div>

    <div class="container pb-3 mb-3">
        <h3>What is reputation?</h3>
        <ul>
            <li class="mb-2">
                It is a rough measurement of how much the community trusts you.
            </li>
            <li class="mb-2">
                It is displayed next to your username.
            </li>
        </ul>
        <h4>You earn reputation when:</h4>
        <ul>
            <li class="mb-2">
                add an entry or translation: +1
            </li>
            <li class="mb-2">
                entry is bookmarked: +2
            </li>
            <li class="mb-2">
                translation is upvoted: +10
            </li>
            <li class="mb-2">
                translation is well-proofread: x correctness %
            </li>
        </ul>
        <h4>You lose reputation when:</h4>
        <ul>
            <li class="mb-2">
                translation is downvoted: -5
            </li>
            <li class="mb-2">
                translation is not well-proofread: x correctness %
            </li>
        </ul>
        <h4>Reputation priviliges</h4>
        <ul>
            <li class="mb-2">
                10 or more: access dictionary defintions, parts of speech and more.
            </li>
            <li class="mb-2">
                20 or more: play games.
            </li>
            <li class="mb-2">
                30 or more: add examples to dictionary entries.
            </li>
        </ul>
        Rise the ranks now!
    </div>
{% endblock %}

users/templates/users/base.html
{% extends 'base.html' %}

{% block title %}
    Aklish Users
{% endblock title %}

{% block main %}
    {% block content %}
    {% endblock %}
{% endblock %}

users/templates/users/bookmarks_votes.html
{% extends 'users/profile_base.html' %}

{% block title %}
    {{ user.username }}'s Bookmarks and Votes
{% endblock title %}

{% block body %}
    <div class="pb-3 mb-3">
        <h2 class="h5">
            Bookmarks
        </h2>
        <ul class="list-group">
            {% for entry in user.bookmarks.all %}
                <li class="list-group-item d-flex align-items-center">
                    <a href="{% url 'translate:entry' entry.pk %}" class="me-auto text-decoration-none">
                        {{ entry.content|slice:100 }}...
                    </a>

                    {% if request.user == user %}
                        <form action="{% url 'translate:bookmark' entry.pk %}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-danger">Remove</button>
                        </form>
                    {% endif %}
                </li>
            {% empty %}
                <li class="list-group-item">
                    No bookmarks
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="pb-3 mb-3">
        <h2 class="h5">
            Votes
        </h2>
        <ul class="list-group">
            {% for vote in user.votes.all %}
                <li class="list-group-item d-flex align-items-center">
                    <a href="{% url 'translate:entry' vote.translation.entry.pk %}" class="me-auto text-decoration-none">
                        {{ vote.translation.content|slice:100 }}...
                    </a>

                    {% if request.user == user %}
                        <form action="{% url 'translate:vote' vote.translation.pk %}" method="POST">
                            {% csrf_token %}
                            <button name="direction" value="0" class="btn btn-sm btn-danger">
                                Remove
                            </button>
                        </form>
                    {% endif %}
                </li>
            {% empty %}
                <li class="list-group-item">
                    No votes
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

users/templates/users/entries_translations.html
{% extends 'users/profile_base.html' %}

{% block title %}
    {{ user.username }}'s Entries and Translations
{% endblock title %}

{% block body %}
    {% include 'users/components/entries_list.html' with entries=user.entries.all title='Entries' %}
    {% include 'users/components/entries_list.html' with entries=user.translations.all title='Translations' %}
{% endblock %}

users/templates/users/index.html
{% extends 'users/base.html' %}

{% load humanize %}

{% block title %}
    Aklish Leaderboard
{% endblock title %}

{% block content %}
    <div class="container pb-3 mb-3 border-bottom">
        <h1>{{ users.count }} users</h1>
    </div>

    <div class="container pb-3 mb-3">
        <!-- Reputation guide -->
        <div class="mb-2">
            <small class="text-muted">
                Learn more about
                <a href="{% url 'main:help' 'reputation_guide' %}" class="text-reset">reputation</a>.
            </small>
        </div>

        <!-- Leaderboard -->
        <ul class="list-group">
            {% for user in users %}
                <li class="list-group-item">
                    <!-- Rank and username -->
                    <div class="d-flex">
                        <div class="me-auto">
                            <span class="me-2">Rank #{{ forloop.counter }}</span>
                        </div>
                        <div>
                            {{ user.profile.reputation }} reputation
                        </div>
                    </div>

                    <!-- Details -->
                    <div class="d-flex">
                        <div class="me-auto">
                            <a href="{% url 'users:profile' user.pk user.username %}" class="text-decoration-none">
                                {{ user.username }}
                            </a>
                        </div>
                        <div class="text-end text-muted">
                            <small>
                                <span class="text-nowrap">member for</span>
                                <span class="text-nowrap">{{ user.date_joined|timesince }}</span>
                            </small>
                        </div>
                    </div>
                </li>
            {% empty %}
                No users
            {% endfor %}
        </ul>
        <!-- End leaderboard -->
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% load static %}

{% block title %}
    Sign in to Aklish
{% endblock title %}

{% block content %}
    <div class="row g-3 m-1 mb-3">
        <div class="col-md-6 d-flex flex-column justify-content-center align-items-center text-center">
            <div class="col-lg-7 col-md-8 col-sm-9 col-10 p-4 mx-auto border rounded-4">
                <h1 class="mb-3 fw-bold">Sign in</h1>

                <div class="mb-3">
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-warning px-2 py-1" role="alert">
                            {{ error|escape }}
                        </div>
                    {% endfor %}

                    <form method="POST" autocomplete="off" class="mb-3">
                        {% csrf_token %}

                        <div class="form-group mb-2">
                            <label for="#username" class="form-label visually-hidden">Username</label>
                            {{ form.username }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="password" class="form-label visually-hidden">Password</label>
                            {{ form.password }}
                        </div>

                        <button class="col-12 btn btn-primary">Sign in</button>
                    </form>
                </div>

                <div class="mb-3">
                    <p class="m-0">Don't have an account? <a href="{% url 'users:register' %}">Sign up</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-6 px-lg-5 d-flex justify-content-center align-items-center">
            <img src="{% static 'images/carabao-reading.svg' %}" alt="Aklish" style="width: 80%; height: auto;">
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/profile_base.html' %}

{% block title %}
    {{ user.username }}'s Profile
{% endblock title %}

{% block body %}
    <!-- Stats -->
    <div class="pb-3 mb-3">
        <h2 class="h5">
            Stats
        </h2>
        <ul class="list-group">
            <li class="list-group-item">
                {{ user.profile.reputation }} reputation
            </li>
            <li class="list-group-item">
                {{ user.entries.count }} entries
            </li>
            <li class="list-group-item">
                {{ user.translations.count }} translations
            </li>
        </ul>
    </div>
    <!-- End stats -->

    <!-- Activity -->
    <div class="pb-3 mb-3">
        <h2 class="h5">
            Activity
        </h2>
        <ul class="list-group">
            <li class="list-group-item">
                <a href="{% url 'users:bookmarks_votes' user.pk user.username %}"
                    class="underline-hover"
                >
                    Bookmarks and Votes
                </a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'users:entries_translations' user.pk user.username %}"
                    class="underline-hover"
                >
                    Entries and Translations
                </a>
            </li>
        </ul>
    </div>
    <!-- End activity -->
{% endblock %}

users/templates/users/profile_base.html
{% extends 'users/base.html' %}

{% block title %}
    {{ user.username }}'s Profile
{% endblock title %}

{% block content %}
    <div class="container px-4">
        <!-- Profile header -->
        <div class="container pb-3 mb-3 border-bottom">
            <div class="d-flex mb-2">
                <!-- Fullname -->
                <h1>{{ user.first_name }} {{ user.last_name }}</h1>

                <!-- Logout button -->
                {% if user == request.user %}
                    <div class="ms-auto d-flex align-items-center">
                        <a href="{% url 'users:logout' %}" class="btn btn-sm border">Logout</a>
                    </div>
                {% endif %}
            </div>

            <div class="text-muted">
                <!-- Activity -->
                <div class="mb-1">
                    <small class="me-2">Member since {{ user.date_joined|date:'d M y' }}</small>
                    <small class="me-2">Last active {{ user.last_login|date:'d M y' }}</small>
                </div>

                <!-- Contact -->
                <div class="mb-1">
                    <small class="me-2">@{{ user.username }}</small>
                    <small class="me-2">{{ user.email }}</small>
                </div>
            </div>
        </div>
        <!-- End profile header -->

        <div class="container">
            {% block body %}{% endblock %}
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% load static %}

{% block title %}
    Sign up to Aklish
{% endblock title %}

{% block content %}
    <div class="row g-3 m-1 mb-3">
        <div class="col-md-6 d-flex flex-column justify-content-center align-items-center text-center">
            <div class="col-lg-7 col-md-8 col-sm-9 col-10 p-4 mx-auto border rounded-4">
                <h1 class="mb-3 fw-bold">Sign up</h1>

                <div class="mb-3">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-warning px-2 py-1" role="alert">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}

                    <form method="POST" autocomplete="off" class="mb-3">
                        {% csrf_token %}

                        <div class="form-group mb-2">
                            <label for="#username" class="form-label visually-hidden">Username</label>
                            {{ form.username }}
                        </div>
                        <div class="form-group mb-2">
                            <label for="#email" class="form-label visually-hidden">Email</label>
                            {{ form.email }}
                        </div>
                        <hr>
                        <div class="form-group mb-2">
                            <label for="#first_name" class="form-label visually-hidden">First name</label>
                            {{ form.first_name }}
                        </div>
                        <div class="form-group mb-2">
                            <label for="#last_name" class="form-label visually-hidden">Last name</label>
                            {{ form.last_name }}
                        </div>
                        <hr>
                        <div class="form-group mb-2">
                            <label for="#password1" class="form-label visually-hidden">Password</label>
                            {{ form.password1 }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="#password2" class="form-label visually-hidden">Confirm Password</label>
                            {{ form.password2 }}
                        </div>

                        <button class="col-12 btn btn-primary">Sign up</button>
                    </form>
                </div>

                <div class="mb-3">
                    <p class="m-0">Already have an account? <a href="{% url 'users:login' %}">Sign in</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-6 px-lg-5 d-flex justify-content-center align-items-center">
            <img src="{% static 'images/carabao-reading.svg' %}" alt="Aklish" style="width: 80%; height: auto;">
        </div>
    </div>
{% endblock %}