aklish/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("users/", include("users.urls")),
    path("translate/", include("translate.urls")),
    path("dictionary/", include("dictionary.urls")),
    path("dictionary/api/", include("dictionary.api.urls")),
    path("proofreader/", include("proofreader.urls")),
    path("proofreader/api/", include("proofreader.api.urls")),
    path("games/", include("games.urls")),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

dictionary/urls.py
from django.urls import path

from . import views


app_name = "dictionary"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:lang>/entries/", views.catalog, name="catalog"),
    path("<str:lang>/entries/<str:letter>/", views.catalog, name="catalog"),
    path("<str:lang>/entry/<str:word>/", views.entry, name="entry"),
    path("<str:lang>/entry/<str:word>/add_example/<int:attribute_pk>/", views.add_example, name="add_example",),
    path("<str:lang>/word_of_the_day/", views.word_of_the_day, name="word_of_the_day"),
]

games/urls.py
from django.urls import path

from . import views


app_name = "games"
urlpatterns = [
    path("wordle/<str:lang>/", views.wordle, name="wordle"),
    path("match/<str:lang>/", views.match, name="match"),
]

main/urls.py
from django.urls import path

from . import views


app_name = "main"
urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("sources/", views.sources, name="sources"),
    path("help/", views.help, name="help"),
    path("help/<str:page>/", views.help, name="help"),
]

translate/urls.py
from django.urls import path

from . import views


app_name = "translate"
urlpatterns = [
    path("entries/", views.catalog, name="catalog"),
    path("entry/<int:entry_pk>/", views.entry, name="entry"),
    path("add/", views.add, name="add"),
    path("edit/entry/<int:entry_pk>/", views.edit_entry, name="edit_entry"),
    path("edit/translation/<int:translation_pk>/", views.edit_translation, name="edit_translation",),
    path("delete/translation/", views.delete_translation, name="delete_translation", ),
    path("delete/entry/", views.delete_entry, name="delete_entry"),
    path("bookmark/<int:entry_pk>/", views.bookmark, name="bookmark"),
    path("vote/<int:translation_pk>/", views.vote, name="vote"),
]

users/urls.py
from django.urls import path

from . import views


app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:user_id>/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/<str:username>/bookmarks_votes/", views.bookmarks_votes, name="bookmarks_votes",),
    path("<int:user_id>/<str:username>/entries_translations/", views.entries_translations, name="entries_translations",),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

main/models.py
from django.db import models

main/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django import template

from translate.models import Entry, Translation
from dictionary.models import DictEntry

from dictionary.helpers import get_word_today


def homepage(request):
    dict_entries = DictEntry.objects.filter(lang__code="akl")
    entry_today = get_word_today(dict_entries)

    top_users = User.objects.filter(is_active=True).filter(is_staff=False).order_by("-profile__reputation")[:3]

    return render(
        request,
        "main/homepage.html",
        {
            "entries": Entry.objects.all(),
            "translations": Translation.objects.all(),
            "dict_entries": DictEntry.objects.all(),
            "entry_today": entry_today,
            "top_users": top_users,
        },
    )


def about(request):
    return render(request, "main/about.html")


def contact(request):
    return render(request, "main/contact.html")


def sources(request):
    return render(request, "main/sources.html")


def help(request, page=None):
    categories = {
        "Translate": {
            "adding_guide": "Guide in adding entries",
            "translating_guide": "Guide in translating entries",
        },
        "Reputation": {
            "reputation_guide": "What is reputation?",
            "reputation_guide": "How to earn reputation?",
            "reputation_guide": "How reputation is loss?",
        },
        "Proofreader": {
            "proofreader_guide": "How to use proofreader?",
            "proofreader_guide": "How does proofreader works?",
        },
        "Games": {
            "match_guide": "How to play Match?",
            "wordle_guide": "How to play Wordle?",
        },
    }

    default_template = "main/help/index.html"

    if not page:
        return render(request, default_template, {
            "categories": categories,
        })

    page_template = f"main/help/{page}.html"

    try:
        template.loader.get_template(page_template)
        return render(request, page_template)
    except template.TemplateDoesNotExist:
        return render(request, default_template, {
            "categories": categories,
        })

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}
    About Aklish
{% endblock %}

{% block content %}
    <!-- About -->
    <article id="about" class="container">
        <!-- Title -->
        <h1 class="pb-3 mb-3 border-bottom">About Aklish</h1>

        <!-- Intro -->
        <section id="intro" class="mb-4">
            <p>
                Welcome to Aklish, your platform for crowdsourcing Aklanon-English translations and fostering language learning and cultural exchange.
            </p>
        </section>
        <!-- End intro -->

        <!-- Mission -->
        <section id="mission" class="mb-4">
            <h2>Our Mission</h2>

            <p>
                At Aklish, our mission is to bridge language barriers and celebrate linguistic diversity
                by empowering Aklanon speakers and foreign learners to contribute and engage with the Aklanon and English languages.
            </p>
        </section>
        <!-- End mission -->

        <!-- Features -->
        <section id="features" class="mb-4">
            <h2>Features</h2>

            <ul>
                <li>
                    <h3 class="fs-5 m-0">Crowdsourced Translations</h3>
                    <p>
                        Aklish allows users to add
                        text entries for translation or
                        contribute their translations to existing text entries.
                    </p>
                </li>
                <li>
                    <h3 class="fs-5 m-0">Aklanon-English Dictionary</h3>
                    <p>
                        Explore our comprehensive dictionary
                        to look up Aklanon and English words,
                        complete with definitions, parts of speech, examples, and more!
                    </p>
                </li>
                <li>
                    <h3 class="fs-5 m-0">Proofreading Tools</h3>
                    <p>
                        Our integrated proofreading tools help users
                        refine their Aklanon and English writing skills,
                        offering spelling suggestions tailored to both languages.
                    </p>
                </li>
                <li>
                    <h3 class="fs-5 m-0">Language Games</h3>
                    <p>
                        Aklish offers a variety of interactive games
                        like Wordle and Match designed
                        to reinforce language skills and vocabulary retention.
                    </p>
                </li>
            </ul>
        </section>
        <!-- End features -->

        <!-- Team -->
        <section id="team" class="mb-4">
            <h2>Meet the Team</h2>

            <div class="mb-2">
                <h3 class="fs-5 m-0">Andrian Lloyd Maagma</h3>
                <small>Student Researcher and Developer</small>
            </div>
        </section>
        <!-- End team -->

        <!-- Contribute -->
        <section id="contribute" class="mb-4">
            <h2>Get Involved</h2>

            <p>
                Join our community of language enthusiasts, educators, and learners!
                Whether you're a native speaker, a language learner,
                or simply passionate about linguistic diversity
                there are plenty of ways to get involved and contribute to Aklish.
            </p>
            <p>
                Thank you for being a part of the Aklish community!
            </p>
        </section>
        <!-- End contribute -->

    </article>
    <!-- End about -->
{% endblock %}

main/templates/main/base.html
{% extends 'base.html' %}

{% block title %}
    Aklish
{% endblock title %}

{% block main %}
    {% block content %}
    {% endblock %}
{% endblock %}

main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block title %}
    Contact Aklish
{% endblock %}

{% block content %}
    <!-- Contact -->
    <article id="contact" class="container">
        <!-- Title -->
        <h1 class="pb-3 mb-3 border-bottom">Contact</h1>

        <!-- Content -->
        <section id="content" class="mb-4">
            <div class="my-4">
            <p>
                Got questions, feedback, or suggestions?
                <br>
                Reach out at
                <a href="mailto:maagmaandrian@gmail.com" class="underline-hover">maagmaandrian@gmail.com</a>
            </p>
        </section>
        <!-- End Content -->
    </article>
    <!-- End contact -->
{% endblock %}

main/templates/main/homepage.html
{% extends 'main/base.html' %}

{% load static %}
{% load humanize %}

{% block title %}
    Aklish: The Aklanon & English platform where your words translate and are translated.
{% endblock %}

{% block content %}
    <!-- Hero -->
    <section id="hero" class="container p-lg-4 p-md-3">
        <div class="row g-3">
            <div class="col-md-6 d-flex flex-column justify-content-center align-items-center text-center">
                <h1 class="display-2 fw-bold text-nowrap">
                    Translate and
                    <br>
                    be translated
                </h1>
                <p>
                    The Aklanon & English platform where your<br>
                    words translate and are translated.
                </p>
                <div>
                    <a href="{% url 'users:register' %}" class="btn btn-primary mb-2 text-nowrap">
                        Get started
                    </a>
                </div>
            </div>
            <div class="col-md-6 px-lg-5 d-flex justify-content-center align-items-center">
                <img src="{% static 'images/carabao-reading.svg' %}" alt="Aklish" style="width: 80%; height: auto;">
            </div>
        </div>
    </section>
    <!-- End hero -->

    <!-- Stats -->
    <section id="stats" class="container p-3 mb-5">
        <hr>
        <h2 class="text-center fw-bold mb-3">Contribute to our growing numbers!</h2>

        <div class="row">
            <div class="col-4 text-center">
                <a href="{% url 'translate:add' %}" class="link-unstyled">
                    <p class="display-5 fw-bold text-primary mb-0">{{ entries.count }}</p>
                    <p class="fs-6">Entries</p>
                </a>
            </div>
            <div class="col-4 text-center">
                <a href="{% url 'translate:catalog' %}" class="link-unstyled">
                    <p class="display-5 fw-bold text-primary mb-0">{{ translations.count }}</p>
                    <p class="fs-6">Translations</p>
                </a>
            </div>
            <div class="col-4 text-center">
                <a href="{% url 'dictionary:catalog' 'akl' %}" class="link-unstyled">
                    <p class="display-5 fw-bold text-primary mb-0">{{ dict_entries.count }}</p>
                    <p class="fs-6">Words</p>
                </a>
            </div>
        </div>
        <hr>
    </section>
    <!-- End stats -->

    <!-- Call to action -->
    <section id="add-entry" class="container p-3 mb-5">
        <div class="row g-3">
            <div class="col-md-6 order-md-1 order-2 px-lg-5 d-flex flex-column justify-content-center align-items-center">
                <textarea id="entry-text-example" name="content"
                class="form-control p-4 mb-3 flex-grow-1 fs-3 border-2 border-primary"
                placeholder="Write what you want to translate here" rows="3"></textarea>

                <a id="add-entry-example" href="{% url 'translate:add' %}" class="btn btn-outline-primary">
                    Add an entry
                </a>
            </div>
            <div class="col-md-6 order-md-2 order-1 d-flex flex-column justify-content-center align-items-center text-md-end text-center">
                <div>
                    <h1 class="display-6 fw-bold text-nowrap">
                        Imong hambae,
                        <br>
                        their translation
                    </h1>
                    <p>
                        Easily submit your text for translation <br> and contribute to the community.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <br>
    <section id="add-translation" class="container p-3 mb-5">
        <div class="row g-3">
            <div class="col-md-6 d-flex flex-column justify-content-center align-items-center text-md-start text-center">
                <div>
                    <h1 class="display-6 fw-bold text-nowrap">
                        Their words,
                        <br>
                        imong pagsalin
                    </h1>
                    <p>
                        Help translate texts submitted by others <br> and make a difference in our shared knowledge.
                    </p>
                </div>
            </div>
            <div class="col-md-6 px-lg-5 d-flex flex-column justify-content-center align-items-center">
                <div class="mb-2">
                    <div class="d-flex align-items-center justify-content-center text-muted">
                        <i class="bi bi-chat-right-quote fs-1 text-primary me-3"></i>
                        <p class="fs-4 fw-bold m-0">The carabao is swimming in the mud.</p>
                    </div>

                    <div class="d-flex align-items-center justify-content-center text-muted">
                        <i class="bi bi-chat-left-quote-fill fs-1 text-primary me-3"></i>
                        <p class="fs-6 fw-bold m-0">Ro anwang nagaeungaeog sa eugan-eugan.</p>
                    </div>
                </div>

                <a href="{% url 'translate:catalog' %}" class="btn btn-outline-primary">
                    Translate an entry
                </a>
            </div>
        </div>
    </section>
    <!-- End call to action -->
    <br>
    <!-- Dictionary -->
    <section id="dictionary" class="container p-3 mb-5">
        <div class="row g-3">
            <div class="col-md-6 order-md-1 order-2 px-lg-5 d-flex flex-column justify-content-center align-items-center">
                {% include 'dictionary/word_today.html' %}
            </div>
            <div class="col-md-6 order-md-2 order-1 d-flex flex-column justify-content-center align-items-center text-md-end text-center">
                <div>
                    <h1 class="display-6 fw-bold text-nowrap">
                        Explore the
                        <br>
                        Dictionary
                    </h1>
                    <p>
                        Dive into comprehensive Aklanon and English dictionaries.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End dictionary -->
    <br>
    <!-- Proofreader -->
    <section id="proofreader" class="container p-3 mb-5">
        <div class="row g-3">
            <div class="col-md-6 d-flex flex-column justify-content-center align-items-center text-md-start text-center">
                <div>
                    <h1 class="display-6 fw-bold text-nowrap">
                        Use the
                        <br>
                        Spellchecker
                    </h1>
                    <p>
                        Verify your Aklanon spelling with our accurate spellchecking tool.
                    </p>
                </div>
            </div>
            <div class="col-md-6 px-lg-5 d-flex flex-column justify-content-center align-items-center">
                <div class="px-5 py-4 mb-3 bg-body-tertiary rounded">
                    <div class="fs-4 mb-3">
                        saea gilang <u class="link-underline-danger">run</u> hay,
                        <u class="link-underline-danger">gapnalapong</u> ka
                    </div>

                    <div class="d-flex flex-wrap fs-5 text-muted">
                        <small class="me-2 text-nowrap">
                            <strong id="word-count">6</strong> words
                        </small>
                        <small class="me-2 text-nowrap">
                            <strong id="mistake-count">2</strong> mistakes
                        </small>
                        <small class="me-2 text-nowrap">
                            <strong id="correctness">33%</strong> correct
                        </small>
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <a href="{% url 'proofreader:index' 'akl' %}" class="btn btn-outline-primary">
                        Try for free
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- End proofreader -->
    <br>
    <!-- Games-->
    <section id="games" class="p-3 mb-5">
        <div class="row g-3">
            <div class="col-md-6 order-md-1 order-2 px-lg-5 d-flex flex-column justify-content-center align-items-center">
                <div class="row g-3">
                    <!-- Wordle -->
                    <div class="col-md">
                        <div class="card h-100 p-2 rounded-4 border-2 border-primary">
                            <div class="card-body d-flex flex-column">
                                <h3 class="card-title fs-4 fw-bold mb-1">Aklanon Wordle</h3>

                                <p class="card-text m-0">
                                    Can you guess the secret Aklanon word in 6 turns?
                                </p>

                                <div class="px-2">
                                    <div class="grid">
                                        <div class="row d-flex">
                                            <div class="misplaced">K</div>
                                            <div class="misplaced">A</div>
                                            <div class="absent">L</div>
                                            <div class="correct">A</div>
                                            <div class="correct">N</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End of wordle -->

                    <!-- Match -->
                    <div class="col-md">
                        <div class="card h-100 p-2 rounded-4">
                            <div class="card-body d-flex flex-column">
                                <h3 class="card-title fs-4 fw-bold mb-1">Aklanon Match</h3>

                                <p class="card-text">
                                    Can you identify the synonym of an Aklanon word?
                                    <div class="p-2 d-flex justify-content-center bg-body-tertiary rounded">
                                        <button class="btn btn-sm btn-outline-primary rounded-pill">
                                            bahoe
                                        </button>
                                        <button class="btn btn-sm btn-danger rounded-pill mx-1">
                                            isot
                                        </button>
                                        <button class="btn btn-sm btn-outline-success rounded-pill">
                                            eagko
                                        </button>
                                    </div>
                                </p>
                            </div>
                        </div>
                    </div>
                    <!-- End of match -->

                    <div class="d-flex justify-content-center">
                        <a href="{% url 'games:wordle' 'akl' %}" class="btn btn-outline-primary">
                            Play now!
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 order-md-2 order-1 d-flex flex-column justify-content-center align-items-center text-md-end text-center">
                <div>
                    <h1 class="display-6 fw-bold text-nowrap">
                        Play Fun
                        <br>
                        Word Games
                    </h1>
                    <p>
                        Challenge yourself with Aklanon and English <br> language games and enhance your skills.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End of games -->
    <br>
    <!-- Leaderboard -->
    <section id="leaderboard" class="p-3 mt-5">
        <h2 class="text-center fw-bold mb-3">Top Contributors</h2>

        <div class="mb-4 d-flex justify-content-center">
            <div class="d-flex flex-column">
                {% for user in top_users %}
                    <div class="fs-5">
                        <span class="me-1">#{{ forloop.counter }}</span>
                        <a href="{% url 'users:profile' user.pk user.username %}" class="text-decoration-none">
                            <i class="bi bi-person"></i>
                            {{ user.username }}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="mt-auto d-flex justify-content-center">
            <a href="{% url 'users:index' %}" class="text-decoration-none fw-bold">
                See leaderboard
                <i class="bi bi-arrow-right"></i>
            </a>
        </div>
    </section>
    <!-- End of leaderboard -->

    <script>
        const addEntryExample = document.querySelector("#add-entry-example");
        const entryTextExample = document.querySelector("#entry-text-example");

        addEntryExample.addEventListener("click", (event) => {
            localStorage.setItem("proofreaderTextInput", entryTextExample.value)
        })
    </script>
{% endblock %}

main/templates/main/sources.html
{% extends 'main/base.html' %}

{% block title %}
    Aklish Sources
{% endblock %}

{% block content %}
    <!-- Sources -->
    <article id="sources" class="container">
        <!-- Title -->
        <h1 class="pb-3 mb-3 border-bottom">Sources</h1>

        <!-- Content -->
        <section id="content">
            <p>Our main data sources are (in random order):</p>

            <!-- List of sources -->
            <ul class="list-group">
                <li class="list-group-item">
                    <a href="https://eric.ed.gov/?id=ED145705" class="underline-hover">
                        A Study of the Aklanon Dialect. Volume One: Grammar.
                    </a><br>
                    <small>
                        Zorc, R. D. P., & de la Cruz, B. A. (1968)
                    </small>
                </li>
                <li class="list-group-item">
                    <a href="https://files.eric.ed.gov/fulltext/ED145704.pdf" class="underline-hover">
                        A Study of the Aklanon Dialect. Volume Two: Dictionary (of root words and derivations) Aklanon to English.
                    </a><br>
                    <small>
                        Reyes, V. S., Zorc, R. D. P., & Prado, N. L. (1969)
                    </small>
                </li>
                <li class="list-group-item">
                    <a href="https://acd.clld.org/languages/226" class="underline-hover">
                        ACD - Austronesian Comparative Dictionary Online
                    </a><br>
                    <small>
                        Blust, R., Trussel, S., Smith, A. D. & Forkel, R. (Accessed 2024)
                    </small>
                </li>
                <li class="list-group-item">
                    <a href="https://www.ibiblio.org/webster/" class="underline-hover">
                        The GNU version of The Collaborative International Dictionary of English, presented in the Extensible Markup Language
                    </a><br>
                    <small>
                        Dyck, M. (2022)
                    </small>
                </li>
            </ul>
            <!-- End list of sources -->

            <p class="mt-4">Thank you.</p>
        </section>
        <!-- End content -->
    </article>
    <!-- End sources -->
{% endblock %}